src/components/report/Tester.css, src/components/report/Tester.js, src/components/report/Tester.vue, src/components/report/TextControls.js, src/components/report/TextControls.vue
This will show a developer the exact HTML and CSS they need to
copy/paste to recreate the situation in the type tester.
=> Show HTML and CSS matching type tester

package-lock.json, src/components/report/VariableControls.js, src/components/report/VariableControls.vue
Small fixes to fully work with actual data from the Wakamai Fondue engine.
=> Variable fixes

package-lock.json, src/components/report/Summary.js, src/components/report/Summary.vue
Depends on https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/6
=> Properly show summary data

package-lock.json, src/components/Report.vue, src/components/report/Tester.vue, src/components/report/TextControls.js
Depends on https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/7
=> Use language systems from font

.github/workflows/ci.yml, babel.config.js, package.json, src/App.js, vue.config.js
This PR adds a basic CI setup with GitHub Actions.
It runs the linter and tries to build the site.
=> Add basic CI

package-lock.json, src/components/Report.vue, src/components/report/FeatureControls.css, src/components/report/FeatureControls.js, src/components/report/FeatureControls.vue, src/components/report/Features.css, src/components/report/Features.js, src/components/report/Features.vue, src/components/report/Summary.js, src/components/report/Summary.vue, src/components/report/Tester.vue, src/components/report/TextControls.vue
=> Use font's layout features in tester

src/components/report/Tester.js
Depends on https://github.com/Wakamai-Fondue/wakamai-fondue-site/pull/55, merge that first.
Fixes #28
=> Use example text

src/components/report/TextControls.vue, src/components/report/Variable.css, src/components/report/VariableControls.css, src/components/report/VariableControls.js, src/components/report/VariableControls.vue
Actually show named instance in use in the named instance buttons
=> Variable buttons

package.json, src/components/report/Summary.css, src/components/report/Summary.js, src/components/report/Summary.vue
Depends on https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/17
=> Show languagesystems in summary, refactoring

src/components/report/VariableControls.js, src/components/report/VariableControls.vue
Currently leaving this WIP until I have a few of these.
=> Various small tweaks and fixes

package-lock.json, package.json, src/App.js
See https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/19 and https://github.com/Wakamai-Fondue/wakamai-fondue-cli/pull/6.
=> Use WF engine via new package name

src/components/report/Features.js, src/components/report/Tester.vue
@pascalw Please review this with all your might! ⚡
=> Fix a big fat oopsie

src/App.css, src/components/report/FeatureControls.css, src/components/report/FeatureControls.js, src/components/report/FeatureControls.vue, src/components/report/Tester.css, src/components/report/Tester.js, src/components/report/Tester.vue
Ticks off "Improve tester layout and colors" from the beta release list.
=> Tester layout improvements

package-lock.json, package.json, src/components/report/CharGrid.css, src/components/report/CharGrid.js, src/components/report/CharGrid.vue, src/filters.js
This might need some more thorough testing, but I'd like to pick
that up in a future request.
Depends on https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/24
=> Show categorised chars

src/components/report/Summary.js, src/components/report/Summary.vue, src/components/report/Tester.js, src/components/report/Tester.vue, src/components/report/TextControls.js, src/components/report/TextControls.vue, src/filters.js
Depends on https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/26
=> Add old language support

public/index.html, src/App.css, src/App.js, src/App.vue, src/components/Modal.vue, src/components/report/CharGrid.css, src/components/report/Features.css, src/components/report/Features.vue, src/components/report/VariableControls.css, vue.config.js
Please see individual commits for each small issue addressed.
=> Bits and pieces

src/components/report/Tester.css, src/components/report/Tester.js, src/components/report/Tester.vue
Move away from the red block, as it is a bit weird. This is neutral
enough to be useful, and more in line with other testable parts
of the site.
=> Tester w/ regular colors

src/App.css, src/App.vue, src/components/Hero.vue, src/components/Modal.css, src/components/Modal.vue, src/components/report/CharGrid.css, src/components/report/CharGrid.vue, src/components/report/Color.css, src/components/report/FeatureControls.css, src/components/report/FeatureControls.js, src/components/report/Features.css, src/components/report/Summary.css, src/components/report/Summary.vue, src/components/report/TextControls.css, src/components/report/VariableControls.css, src/components/report/VariableControls.js, src/components/report/VariableControls.vue
See individual commits for more details!
=> Dots on i — another round of small fixes

src/components/report/FeatureControls.css, src/components/report/FeatureControls.js, src/components/report/FeatureControls.vue, src/components/report/Features.js, src/components/report/Features.vue
As per https://github.com/Wakamai-Fondue/wakamai-fondue-site/issues/90
Depends on https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/34
=> Add lookup type 3

src/components/report/CharGrid.js, src/components/report/CharGrid.vue, src/components/report/Summary.js, src/components/report/Summary.vue, src/components/report/VariableControls.css, src/components/report/VariableControls.vue
Depends on https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/39
=> Feature small touches

package-lock.json, package.json, src/components/report/Summary.vue, vue.config.js
=> Add hinting info, update reference to engine

src/components/report/Stylesheet.css, src/components/report/Stylesheet.js, src/components/report/Stylesheet.vue, src/components/report/Summary.vue
(Needs the engine to return the new "slug")
=> Add download button for the CSS.

src/components/Modal.vue, src/components/report/Summary.css, src/components/report/Summary.vue, src/components/report/Tester.css, src/components/report/Tester.js, src/components/report/Tester.vue, src/components/report/TextControls.js
A collection of small tweaks that were quicker to implement than to create issues for :-)
=> Little tweakle

src/components/CopyToClipboard.css, src/components/CopyToClipboard.js, src/components/CopyToClipboard.vue, src/components/report/Stylesheet.css, src/components/report/Stylesheet.js, src/components/report/Stylesheet.vue, src/components/report/Tester.css, src/components/report/Tester.js, src/components/report/Tester.vue, src/components/report/Variable.css, src/components/report/Variable.js, src/components/report/Variable.vue, src/components/report/VariableControls.css, src/components/report/VariableControls.js, src/components/report/VariableControls.vue
(Merge https://github.com/Wakamai-Fondue/wakamai-fondue-site/pull/112 first)
Relevant commits start at commit dc75aa1
This adds a 📋 button to all code segments so you can easily copy CSS to the clipboard.
=> Copy to clipboard

package-lock.json, package.json, src/components/CopyToClipboard.css, src/components/Footer.vue, src/components/report/Tester.css, src/components/report/Variable.css
Merge https://github.com/Wakamai-Fondue/wakamai-fondue-site/pull/125 first!
=> More small tweaks

package-lock.json, package.json
=> Dump Wakamai Fondue engine

package-lock.json, package.json
Stuck with older Prettier as I didn't feel like going through the update hassle...
=> Auditing and updating packages

src/components/report/TextControls.js, src/components/report/TextControls.vue, src/components/report/TypeTester.js, src/components/report/TypeTester.vue, src/components/report/VariableControls.js, src/components/report/VariableControls.vue
TODO/Notes
- Fix flipState in axis on/off buttons
=> Fix tester controls

src/components/FileDrop.vue
Addresses some minor things
Fixes #217
=> Various fondue fixes

src/App.vue, src/components/FontSizeSlider.vue, src/components/report/TextControls.vue, src/components/report/TypeTester.vue, src/components/report/VariableControls.vue, src/components/report/VariableFont.vue
The current list isn't very helpful so for now, make the variable tester more useful by offering an old school dropdown.
Next up I wanna add a button that says "Preview all instances" or something, which will then expand a list of simple previews.
Also, there's the Big Ass Tester above this one in the interface, which makes me wonder if all that repetition is servering a purpose. Maybe the first tester should be more preview-y, not showing the internals. For example, offer the instances but not the axes. Just the stuff you'd get in a regular word processor or something.
=> Better variable tester
